"""Helpers for testing the Elro Connects integration."""

MOCK_DEVICE_STATUS_DATA = {
    1: {
        "device_type": "FIRE_ALARM",
        "signal": 3,
        "battery": 100,
        "device_state": "NORMAL",
        "device_status_data": {
            "cmdId": 19,
            "device_ID": 1,
            "device_name": "0013",
            "device_status": "0364AAFF",
        },
        "device_value": "0xff",
        "device_value_data": 255,
        "name": "Beganegrond",
    },
    2: {
        "device_type": "FIRE_ALARM",
        "signal": 4,
        "battery": 75,
        "device_state": "ALARM",
        "device_status_data": {
            "cmdId": 19,
            "device_ID": 2,
            "device_name": "0013",
            "device_status": "044B55FF",
        },
        "device_value": "0xff",
        "device_value_data": 255,
        "name": "Eerste etage",
    },
    4: {
        "device_type": "FIRE_ALARM",
        "signal": 1,
        "battery": 5,
        "device_state": "UNKNOWN",
        "device_status_data": {
            "cmdId": 19,
            "device_ID": 4,
            "device_name": "0013",
            "device_status": "0105FEFF",
        },
        "device_value": "0xff",
        "device_value_data": 255,
        "name": "Zolder",
    },
    5: {
        "device_type": "CO_ALARM",
        "signal": 255,
        "battery": 255,
        "device_state": "OFFLINE",
        "device_status_data": {
            "cmdId": 19,
            "device_ID": 5,
            "device_name": "2008",
            "device_status": "FFFFFFFF",
        },
        "device_value": "0xff",
        "device_value_data": 255,
        "name": "Corner",
    },
    6: {
        "name": "Device with unknown state",
    },
    7: {
        "device_type": "SOCKET",
        "signal": 255,
        "battery": 255,
        "device_state": "NORMAL",
        "device_status_data": {
            "cmdId": 19,
            "device_ID": 5,
            "device_name": "1200",
            "device_status": "04FF0100",
        },
        "device_value": "off",
        "device_value_data": 1,
        "name": "Wall switch off",
    },
    8: {
        "device_type": "SOCKET",
        "signal": 255,
        "battery": 255,
        "device_state": "NORMAL",
        "device_status_data": {
            "cmdId": 19,
            "device_ID": 5,
            "device_name": "1200",
            "device_status": "04FF0101",
        },
        "device_value": "on",
        "device_value_data": 1,
        "name": "Wall switch on",
    },
}


MOCK_AUTH_RESPONSE = {
    "access_token": "eyasdfklasdfjalskdfjlasdggffghdfghdf.edsfgsdhJHDkdaskjdksdfyJ1aWQiOiI3OTQ5NjdfghdfghdfghdfghdfghdfghdghfghhgfhhfghfgdhfdgfghdfghzOCwianRpIjoiYTBkNzQxMTctZDQxNi00ZmUwLWI2YWEtNTMxOGUzY2QxYWM3Iiwicm9sZXMiOltdfSAg.B9ESpw7LFzHRFWxrtF44iX3CDNuQcYYAP0BQSZwN_nqOCETsa1xFq961klvPhkfHYilhJWDTqZygNyfYQJUwvg==",
    "refresh_token": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI3OTQ5NjQ0OTI0NSIsInBpZCI6IjAxMjg4MTU0MTQ2IiwidHlwZSI6IkFQUCIsImV4cCI6MTY2MTg1OTkzOCwianRpIjoiMjcxYzg1ZDEtMTE3MS00MTJlLThkMjktNzhiNDRjYjZiMTU1Iiwicm9sZXMiOltdLCJhdGkiOiJhMGQ3NDExNy1kNDE2LTRmZTAtYjZhYS01MzE4ZTNjZDFhYzcifSAg.K3nUsdfgsdfgsdfgsdfgsdfhghfjjfghjfghjfghjfghjdghjdfhfdghdfghdfghsdfgsdfhfgdghdfghdfghh==",
    "expires_in": 86400,
    "token_type": "bearer",
    "user": "79123456789",
}

MOCK_DEVICE_RESPONSE = [
    {
        "ctrlKey": "deadbeefdeadbeefdeadbeefdeadbeef",
        "devTid": "ST_deadbeef0000",
        "devType": "INDEPENDENT",
        "mid": "0123456789ab",
        "bindKey": "beefdead012345678beefdead0123456",
        "workModeType": "JSON_CTRL",
        "ssid": "HEKR-TEST",
        "rssi": None,
        "mac": "deadbeef012",
        "gis": {
            "ip": {
                "country": None,
                "province": None,
                "city": "内网IP",
                "citycode": None,
                "district": None,
                "adcode": None,
                "township": None,
                "towncode": None,
                "street": None,
                "ip": "10.0.0.1",
            },
            "geo": None,
            "bs": None,
            "bsOther": None,
        },
        "dcInfo": {
            "fromDC": "fra",
            "dc": None,
            "area": "",
            "fromArea": "eu",
            "remoteDomain": "hekreu.me",
            "domain": "hekr.me",
            "connectHost": "fra-hub.hekreu.me",
        },
        "lanIp": None,
        "devKey": None,
        "lanIpUpdateDate": 1658855873540,
        "binVersion": "2.0.3.30",
        "binType": "B",
        "sdkVer": "2.0.3.30",
        "mcuVer": None,
        "ownerUid": "79123456789",
        "granted": False,
        "forceBind": False,
        "productPublicKey": "k0wfHypbzGlO9coR3asomepublickeyOSuZM332invalidkeyfffwadffwqQT/wP2",
        "logo": "https://allinone-ufile.hekr.me/category/a52db783-bb20-4e64-ba5f-76f7cf2bd4fd/door1.png",
        "androidH5Page": "",
        "iosH5Page": "",
        "weChatH5Page": "",
        "webH5Page": None,
        "iosPageZipURL": None,
        "androidPageZipURL": None,
        "weChatPageZipURL": None,
        "webPageZipURL": None,
        "productBand": "",
        "model": "188A",
        "cidName": "家居家装/报警器",
        "categoryName": {"zh_CN": "家居家装/报警器", "en_US": "Misc/Alarm"},
        "productName": {
            "zh_CN": "我的家",
            "en_US": "My Home",
            "de_DE": "Mein Zuhause",
            "fr_FR": "Chez moi",
            "es_ES": "Mi hogar",
        },
        "online": True,
        "bindResultCode": None,
        "bindResultMsg": None,
        "quickOperationConfigList": [],
        "deviceSort": -1,
        "deviceName": "My Home",
        "name": "My Home",
        "desc": None,
        "folderSort": -1,
        "features": None,
        "folderId": "0",
        "folderName": "root",
        "showType": "COMMON",
        "subDevices": [],
    }
]

MOCK_USER = "test@example.com"
MOCK_PASSWORD = "somepassword"
