#!/bin/sh
# Resolve all dependencies that the application requires to run.
# Stop on errors
set -e

cd "$(dirname "$0")/.."

echo "Installing test and development dependencies..."
uv pip install -r requirements_test.txt
